version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Installing dependencies..."
      - dotnet tool install -g Amazon.Lambda.Tools # Install Lambda CLI tools
      - dotnet tool list -g #list global dotnet tools.
  build:
    commands:
      - echo "Restoring dependencies..."
      - dotnet restore
      - echo "Building the project..."
      - dotnet clean #clean the build.
      - dotnet build -c Release
      - echo "Running tests..."
  post_build:
    commands:
      - echo "Packaging Lambda function..."
      - cd GenAIInstructionsLambda
      - dotnet lambda package -c Release -o ../deploy-package.zip
      - aws s3 cp ../deploy-package.zip s3://codepipeline-us-east-2-48698031604/GenAI-Instructions-P/deploy-package.zip
      - aws s3 cp lambda-template.yml s3://codepipeline-us-east-2-48698031604/GenAI-Instructions-P/BuildArti/lambda-template.yml #copy the cloudformation template to s3, specifying the object key.
artifacts:
  files:
    - deploy-package.zip
    - lambda-template.yml #add the template file to the artifacts.
  discard-paths: yes