AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: GenAIInstructionsLambda::GenAIInstructionsLambda.Function::FunctionHandler
      Runtime: dotnet8
      CodeUri: s3://codepipeline-us-east-2-48698031604/GenAI-Instructions-P/deploy-package.zip
      Role: arn:aws:iam::503561441421:role/CodePipelineExecutionRole
      Timeout: 30 # Optional: Set the timeout for the function in seconds.
      MemorySize: 128 # Optional: Set the memory allocation for the function in MB.
      Environment: # Optional: Define environment variables.
        Variables:
          MY_VARIABLE: "my_value"